#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

from pathlib import Path
import sys
import tempfile
import unittest
from unittest import mock


TOOLS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS_DIR))

import bootstrap
from m0_common import load_manifest


SKIA_REVISION = "587c5b0f5a7b0260826a0c19094c2d952195066e"
SKIA_PORT_REVISION = "eba7a9942690181b9df56538c0d8302c9643fdb1"


def test_manifest() -> dict[str, object]:
    return {
        "git_dependencies": {
            "skia": {
                "path": "third_party/skia",
                "upstream_revision": SKIA_REVISION,
                "revision": SKIA_PORT_REVISION,
            }
        },
        "skia_lastchange": {
            "dependency": "skia",
            "revision": SKIA_REVISION,
            "header_path": "skia/ext/skia_commit_hash.h",
            "version_macro": "SKIA_COMMIT_HASH",
        },
    }


def write_deps(repo_root: Path, *, macro: str = "SKIA_COMMIT_HASH") -> None:
    (repo_root / "DEPS").write_text(
        "\n".join(
            (
                "hooks = [",
                "  {",
                "    'name': 'lastchange_skia',",
                "    'pattern': '.',",
                "    'action': ['python3', "
                "'src/build/util/lastchange.py',",
                f"               '-m', '{macro}',",
                "               '-s', 'src/third_party/skia',",
                "               '--header', "
                "'src/skia/ext/skia_commit_hash.h'],",
                "  },",
                "]",
                "",
            )
        ),
        encoding="utf-8",
    )


def expected_header(revision: str = SKIA_REVISION) -> str:
    return (
        "/* Generated by lastchange.py, do not edit.*/\n"
        "\n"
        "#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_\n"
        "#define SKIA_EXT_SKIA_COMMIT_HASH_H_\n"
        "\n"
        f'#define SKIA_COMMIT_HASH "{revision}"\n'
        "\n"
        "#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_\n"
    )


class SkiaLastchangeManifestTest(unittest.TestCase):
    def test_manifest_matches_skia_upstream_pin_and_deps_hook(self) -> None:
        manifest = load_manifest()
        skia = manifest["git_dependencies"]["skia"]
        lastchange = manifest["skia_lastchange"]
        self.assertEqual(lastchange["revision"], skia["upstream_revision"])
        self.assertEqual(skia["revision"], SKIA_PORT_REVISION)
        bootstrap.verify_skia_lastchange_deps_hook(manifest)


class SkiaLastchangeBootstrapTest(unittest.TestCase):
    def test_install_and_verify_use_pinned_upstream_revision(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            header_path = repo_root / "skia/ext/skia_commit_hash.h"
            header_path.parent.mkdir(parents=True)
            header_path.write_text(
                expected_header(SKIA_PORT_REVISION),
                encoding="utf-8",
            )
            with mock.patch.object(bootstrap, "REPO_ROOT", repo_root):
                bootstrap.ensure_skia_lastchange(manifest, install=True)
                bootstrap.ensure_skia_lastchange(manifest, install=False)

            self.assertEqual(
                header_path.read_text(encoding="utf-8"),
                expected_header(),
            )

    def test_verify_only_rejects_missing_corrupt_and_stale_header(
        self,
    ) -> None:
        cases = (
            ("missing", None, "has not been generated"),
            ("corrupt", "corrupt", "generated Skia commit header mismatch"),
            (
                "stale",
                expected_header("0" * 40),
                "generated Skia commit header mismatch",
            ),
        )
        for name, contents, error in cases:
            with self.subTest(case=name), tempfile.TemporaryDirectory() as tmp:
                repo_root = Path(tmp)
                write_deps(repo_root)
                if contents is not None:
                    header_path = (
                        repo_root / "skia/ext/skia_commit_hash.h"
                    )
                    header_path.parent.mkdir(parents=True)
                    header_path.write_text(contents, encoding="utf-8")
                with (
                    mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                    self.assertRaisesRegex(bootstrap.M0Error, error),
                ):
                    bootstrap.ensure_skia_lastchange(
                        test_manifest(), install=False
                    )

    def test_revision_must_match_dependency_upstream_pin(self) -> None:
        manifest = test_manifest()
        manifest["skia_lastchange"]["revision"] = "0" * 40
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "Skia lastchange revision pin mismatch",
                ),
            ):
                bootstrap.ensure_skia_lastchange(manifest, install=True)

    def test_rejects_parent_symlink_escape(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_root = Path(temporary_directory)
            repo_root = temporary_root / "checkout"
            outside_root = temporary_root / "outside"
            repo_root.mkdir()
            outside_root.mkdir()
            (repo_root / "skia").symlink_to(
                outside_root, target_is_directory=True
            )
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "Skia commit header path escapes the repository",
                ),
            ):
                bootstrap.ensure_skia_lastchange(manifest, install=True)
            self.assertFalse(
                (outside_root / "ext/skia_commit_hash.h").exists()
            )

    def test_rejects_deps_hook_drift(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root, macro="WRONG_SKIA_COMMIT_HASH")
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "lastchange_skia hook is missing",
                ),
            ):
                bootstrap.ensure_skia_lastchange(manifest, install=True)


if __name__ == "__main__":
    unittest.main()
