#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

from pathlib import Path
import sys
import tempfile
import unittest
from unittest import mock


TOOLS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS_DIR))

import bootstrap
from m0_common import load_manifest


DAWN_REVISION = "d089fc91e7e4881362463faf8efe9ae435e34660"
DAWN_PORT_REVISION = "bf197d90cc80ca4e1391953cfb7d57ce8b334bea"


def test_manifest() -> dict[str, object]:
    return {
        "git_dependencies": {
            "dawn": {
                "path": "third_party/dawn",
                "upstream_revision": DAWN_REVISION,
                "revision": DAWN_PORT_REVISION,
            }
        },
        "dawn_lastchange": {
            "dependency": "dawn",
            "revision": DAWN_REVISION,
            "revision_path": "gpu/webgpu/DAWN_VERSION",
            "header_path": "gpu/webgpu/dawn_commit_hash.h",
            "version_macro": "DAWN_COMMIT_HASH",
        },
    }


def write_deps(repo_root: Path, *, macro: str = "DAWN_COMMIT_HASH") -> None:
    (repo_root / "DEPS").write_text(
        "\n".join(
            (
                "hooks = [",
                "  {",
                "    'name': 'lastchange_dawn',",
                "    'pattern': '.',",
                "    'action': ['python3', "
                "'src/build/util/lastchange.py',",
                f"               '-m', '{macro}',",
                "               '-s', 'src/third_party/dawn',",
                "               '--revision', "
                "'src/gpu/webgpu/DAWN_VERSION',",
                "               '--header', "
                "'src/gpu/webgpu/dawn_commit_hash.h'],",
                "  },",
                "]",
                "",
            )
        ),
        encoding="utf-8",
    )


class DawnLastchangeManifestTest(unittest.TestCase):
    def test_manifest_matches_dawn_pin_and_deps_hook(self) -> None:
        manifest = load_manifest()
        dawn = manifest["git_dependencies"]["dawn"]
        lastchange = manifest["dawn_lastchange"]
        self.assertEqual(lastchange["revision"], dawn["upstream_revision"])
        self.assertEqual(dawn["revision"], DAWN_PORT_REVISION)
        bootstrap.verify_dawn_lastchange_deps_hook(manifest)


class DawnLastchangeBootstrapTest(unittest.TestCase):
    def test_install_and_verify_use_pinned_upstream_revision(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            with mock.patch.object(bootstrap, "REPO_ROOT", repo_root):
                bootstrap.ensure_dawn_lastchange(manifest, install=True)
                bootstrap.ensure_dawn_lastchange(manifest, install=False)

                revision_path = repo_root / "gpu/webgpu/DAWN_VERSION"
                header_path = repo_root / "gpu/webgpu/dawn_commit_hash.h"
                self.assertEqual(revision_path.read_text(), DAWN_REVISION)
                self.assertEqual(
                    header_path.read_text(),
                    "/* Generated by lastchange.py, do not edit.*/\n"
                    "\n"
                    "#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_\n"
                    "#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_\n"
                    "\n"
                    f'#define DAWN_COMMIT_HASH "{DAWN_REVISION}"\n'
                    "\n"
                    "#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_\n",
                )

                header_path.write_text("corrupt", encoding="utf-8")
                with self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "generated Dawn commit header mismatch",
                ):
                    bootstrap.ensure_dawn_lastchange(
                        manifest, install=False
                    )

    def test_revision_must_match_dependency_upstream_pin(self) -> None:
        manifest = test_manifest()
        manifest["dawn_lastchange"]["revision"] = "0" * 40
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "Dawn lastchange revision pin mismatch",
                ),
            ):
                bootstrap.ensure_dawn_lastchange(manifest, install=True)

    def test_rejects_manifest_path_traversal(self) -> None:
        manifest = test_manifest()
        manifest["dawn_lastchange"]["revision_path"] = "../../escape"
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "Dawn revision path mismatch",
                ),
            ):
                bootstrap.ensure_dawn_lastchange(manifest, install=True)

    def test_rejects_parent_symlink_escape(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_root = Path(temporary_directory)
            repo_root = temporary_root / "checkout"
            outside_root = temporary_root / "outside"
            repo_root.mkdir()
            outside_root.mkdir()
            (repo_root / "gpu").symlink_to(
                outside_root, target_is_directory=True
            )
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "Dawn revision path escapes the repository",
                ),
            ):
                bootstrap.ensure_dawn_lastchange(manifest, install=True)
            self.assertFalse(
                (outside_root / "webgpu/DAWN_VERSION").exists()
            )

    def test_rejects_deps_hook_drift(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root, macro="WRONG_DAWN_COMMIT_HASH")
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "lastchange_dawn hook is missing",
                ),
            ):
                bootstrap.ensure_dawn_lastchange(manifest, install=True)


if __name__ == "__main__":
    unittest.main()
