#!/usr/bin/env python3
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

from pathlib import Path
import sys
import tempfile
import unittest
from unittest import mock


TOOLS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS_DIR))

import bootstrap
from m0_common import load_manifest


CHROMIUM_REVISION = "24b04c927b23c39cf9c5227cc8dc6f64a744c8e9"


def test_manifest() -> dict[str, object]:
    return {"chromium": {"revision": CHROMIUM_REVISION}}


def write_deps(
    repo_root: Path,
    *,
    macro: str = "GPU_LISTS_VERSION",
    action_suffix: str = "",
) -> None:
    (repo_root / "DEPS").write_text(
        "\n".join(
            (
                "hooks = [",
                "  {",
                "    'name': 'gpu_lists_version',",
                "    'pattern': '.',",
                "    'action': ['python3', "
                "'src/build/util/lastchange.py',",
                f"               '-m', '{macro}',",
                "               '--revision-id-only',",
                "               '--header', "
                "'src/gpu/config/gpu_lists_version.h'"
                f"{action_suffix}],",
                "  },",
                "]",
                "",
            )
        ),
        encoding="utf-8",
    )


def expected_header(revision: str = CHROMIUM_REVISION) -> str:
    return (
        "/* Generated by lastchange.py, do not edit.*/\n"
        "\n"
        "#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_\n"
        "#define GPU_CONFIG_GPU_LISTS_VERSION_H_\n"
        "\n"
        f'#define GPU_LISTS_VERSION "{revision}"\n'
        "\n"
        "#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_\n"
    )


class GpuListsVersionManifestTest(unittest.TestCase):
    def test_manifest_matches_chromium_pin_and_deps_hook(self) -> None:
        manifest = load_manifest()
        self.assertEqual(manifest["chromium"]["revision"], CHROMIUM_REVISION)
        bootstrap.verify_gpu_lists_version_deps_hook(manifest)


class GpuListsVersionBootstrapTest(unittest.TestCase):
    def test_install_and_verify_use_pinned_chromium_revision(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            header_path = repo_root / "gpu/config/gpu_lists_version.h"
            header_path.parent.mkdir(parents=True)
            header_path.write_text(
                expected_header("0" * 40), encoding="utf-8"
            )
            with mock.patch.object(bootstrap, "REPO_ROOT", repo_root):
                bootstrap.ensure_gpu_lists_version(manifest, install=True)
                bootstrap.ensure_gpu_lists_version(manifest, install=False)

            self.assertEqual(header_path.read_text(), expected_header())

    def test_verify_only_rejects_missing_corrupt_and_stale_header(
        self,
    ) -> None:
        cases = (
            ("missing", None, "has not been generated"),
            (
                "corrupt",
                "corrupt",
                "generated GPU lists version header mismatch",
            ),
            (
                "stale",
                expected_header("0" * 40),
                "generated GPU lists version header mismatch",
            ),
        )
        for name, contents, error in cases:
            with self.subTest(case=name), tempfile.TemporaryDirectory() as tmp:
                repo_root = Path(tmp)
                write_deps(repo_root)
                if contents is not None:
                    header_path = repo_root / "gpu/config/gpu_lists_version.h"
                    header_path.parent.mkdir(parents=True)
                    header_path.write_text(contents, encoding="utf-8")
                with (
                    mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                    self.assertRaisesRegex(bootstrap.M0Error, error),
                ):
                    bootstrap.ensure_gpu_lists_version(
                        test_manifest(), install=False
                    )

    def test_rejects_invalid_chromium_revision(self) -> None:
        manifest = test_manifest()
        manifest["chromium"]["revision"] = "0" * 39  # type: ignore[index]
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "Chromium revision for GPU lists version must be",
                ),
            ):
                bootstrap.ensure_gpu_lists_version(manifest, install=True)

    def test_rejects_parent_symlink_escape(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_root = Path(temporary_directory)
            repo_root = temporary_root / "checkout"
            outside_root = temporary_root / "outside"
            repo_root.mkdir()
            outside_root.mkdir()
            (repo_root / "gpu").symlink_to(
                outside_root, target_is_directory=True
            )
            write_deps(repo_root)
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "GPU lists version header path escapes the repository",
                ),
            ):
                bootstrap.ensure_gpu_lists_version(manifest, install=True)
            self.assertFalse(
                (outside_root / "config/gpu_lists_version.h").exists()
            )

    def test_rejects_deps_hook_drift(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(repo_root, macro="WRONG_GPU_LISTS_VERSION")
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "gpu_lists_version hook is missing",
                ),
            ):
                bootstrap.ensure_gpu_lists_version(manifest, install=True)

    def test_rejects_deps_hook_action_override(self) -> None:
        manifest = test_manifest()
        with tempfile.TemporaryDirectory() as temporary_directory:
            repo_root = Path(temporary_directory)
            write_deps(
                repo_root,
                action_suffix=", '-s', 'src/other-source'",
            )
            with (
                mock.patch.object(bootstrap, "REPO_ROOT", repo_root),
                self.assertRaisesRegex(
                    bootstrap.M0Error,
                    "gpu_lists_version action mismatch",
                ),
            ):
                bootstrap.ensure_gpu_lists_version(manifest, install=True)


if __name__ == "__main__":
    unittest.main()
