# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(enable_chromium_wasm_port)
assert(is_wasm)

executable("m1_base_smoke") {
  sources = [ "m1_base_smoke.cc" ]
  deps = [ "//base:base_wasm_primitives" ]

  no_default_deps = true
  use_libcxx_modules = false
  configs -= [ "//build/config/compiler:runtime_library" ]
}

executable("m1_task_smoke") {
  sources = [ "m1_task_smoke.cc" ]
  deps = [ "//base:base_wasm_task_runtime" ]

  no_default_deps = true
  use_libcxx_modules = false
  configs -= [ "//build/config/compiler:runtime_library" ]
}
